from collections import defaultdict

SELECTED_PRORPERTIES = {'P31': 'is a', 'P50': 'has author', 'P131': 'located in', 'P407': 'language', 'P106': 'occupation',
                        'P21': 'sex or gender', 'P27': 'country of citizenship', 'P361': 'part of',
                        'P19': 'place of birth', 'P276': 'located in', 'P69': 'educated at',
                        'P1412': 'language spoken, written or signed', 'P527': 'has part', 'P641':'played the sport',
                        'P108': 'employer', 'P136': 'genre', 'P39': 'position held', 'P161': 'cast member',
                        'P495': 'country of origin', 'P166': 'award received', 'P20': 'place of death', 'P186': 'made from material',
                        'P170': 'creator', 'P1344': 'has participant', 'P180': 'depicts', 'P126': 'maintained by', 'P137': 'operator',
                        'P175': 'performer', 'P102': 'member of political party', 'P127': 'owned by', 'P140': 'religion',
                        'P159': 'headquarter location', 'P710': 'participant', 'P463': 'member of', 'P413': 'position played',
                        'P364': 'original language', 'P2094': 'competition class', 'P123': 'publisher', 'P2868': 'role',
                        'P264':'record label', 'P937': 'work location', 'P57': 'director',
                        'P184': 'doctoral advisor', 'P551': 'residence', 'P103': 'native language', 'P291': 'place of publication',
                        'P1050': 'medical condition', 'P1346': 'winner', 'P101': 'field of work', 'P7937': 'form or work',
                        'P607': 'conflict', 'P119': 'place of burial', 'P1303': 'instrument', 'P86': 'composer',
                        'P118': 'league', 'P58': 'screenwriter', 'P437': 'distribution format', 'P162': 'producer',
                        'P859': 'sponsor', 'P172': 'ethnicity', 'P275': 'copyright license', 'P750': 'distributed by',
                        'P1923': 'participating team', 'P512': 'academic degree', 'P176': 'manufacturer',
                        'P149': 'architectural style', 'P2079': 'fabrication method', 'P1441': 'present in work',
                        'P272': 'production company', 'P509': 'cause of death', 'P241': 'military branch',
                        'P1196': 'manner of death', 'P452': 'industry', 'P344': 'director of photography',
                        'P840': 'narrative location', 'P449': 'original broadcaster', 'P664': 'organizer',
                        'P1066': 'student of', 'P1071': 'location of creation', 'P206': 'located in or next to body of water',
                        'P84': 'architect', 'P485': 'archives at', 'P1411': 'nominated for', 'P8047': 'country of registry',
                        'P945': 'allegiance', 'P135': 'movement', 'P725': 'voice actor', 'P97': 'noble title',
                        'P144': 'based on', 'P825': 'dedicated to', 'P467': 'legislated by', 'P740': 'location of formation',
                        'P178': 'developer', 'P767': 'contributor to creative work or subject', 'P676': 'lyrics written by',
                        'P3018': 'located in protected area', 'P658': 'tracklist', 'P98': 'editor', 'P371': 'presenter',
                        'P611': 'religious order', 'P1080': 'from narrative universe', 'P189': 'location of discovery',
                        'P8345': 'media franchise', 'P88': 'commissioned by', 'P1142': 'political ideology',
                        'P547': 'commemorates', 'P532': 'port of registry', 'P737': 'influenced by',
                        'P2341': 'indigenous to', 'P2541': 'operating area', 'P655': 'translator', 'P1716': 'brand',
                        'P2650': 'interested in', 'P287': 'designed by', 'P110': 'illustrator', 'P289': 'vessel class',
                        'P2515': 'costume designer', 'P647': 'drafted by', 'P6087': 'coach of sports team',
                        'P1399': 'convicted of', 'P4068': 'scenographer', 'P2596': 'culture',
                        'P7153': 'significant place', 'P1431': 'executive producer', 'P1875':'represented by',
                        'P3301': 'broadcast by', 'P1951': 'investor', 'P736': 'cover art by', 'P504': 'home port',
                        'P6241':'collection creator', 'P520': 'armament', 'P941': 'inspired by', 'P4584': 'first appearance',
                        'P1809': 'choreographer', 'P6942': 'animator', 'P618': 'source of energy', 'P3300': 'musical conductor',
                        'P5202': 'adapted by', 'P5028': 'sound designer', 'P6872': 'has written for', 'P812': 'academic major',
                        'P6193': 'ratified by', 'P7936': 'business model', 'P1049': 'worshipped by', 'P2438':'narrator',
                        'P2652': 'partnership with', 'P6338': 'colorist', 'P3174': 'art director', 'P6379': 'has work in the collection',
                        'P410': 'military rank', 'P54': 'played for',
                        'P61': 'discoverer or inventor', 'P306': 'Operating system',
                        'P1080': 'from narrative universe', 'P189': 'location of discovery', 'P1071': 'location of creation',
                        'P275': 'voice actor'}


PROP_SENTENCES = {'P131': [2, 'Which {} is located in {}?'], 'P31': [2, 'What {} is a {}?'], 'P530': [2, 'Which {} does {} have diplomatic relations with?'],
                  'P407': [2, 'Which {} was produced in {}?'], 'P106': [1, 'Who works or worked as a {}?'],
                  'P50': [1, 'Which books were written by {}?'], 'P21': [1, 'Who has or had {} for gender?'],
                  'P27': [1, 'Who is a citizen from {}?'], 'P361': [2, 'Of which {} is {} a part of?'],
                  'P19': [1, 'Who was born in {}?'], 'P276': [2, 'Which {} is located in {}?'],
                  'P69': [1, 'Who is a {} alumni?'], 'P1412': [1, 'Who spoke or wrote in {}?'],
                  'P54': [1, 'Who played for the {}?'], 'P108': [1, 'Who works for {}?'], 'P3373': [1, "Who are the siblings of {}?"],
                  'P136': [2, 'Which {} is from the genre or performed in the genre {}?'],
                  'P39': [1, 'Who held the position {}?'], 'P84': [1, 'Which buildings were designed by {}?'],
                  'P161': [2, 'Which {} has {} as a member of its cast'], 'P495': [2, 'What {} is from {}?'],
                  'P166': [1, 'Who received the award {}?'], 'P20': [1, 'Who died in {}?'],
                  'P186': [2, 'Which {} is made from {}?'], 'P170': [2, 'Which {} was created by {}?'],
                  'P180': [2, 'Which {} depicts {}?'], 'P2868': [2, 'Which {} has a role of {}?'],
                  'P512': [1, 'Who has or had a degree of {}?'], 'P175': [2, 'Which {} has {} as performer?'],
                  'P102': [1, 'Who was a member of the political party {}?'],
                  'P127': [2, 'Which {} is owned by {}?'], 'P159': [2, 'Which {} has or had its headquarters in {}?'],
                  'P710': [2, 'Which {} had {} as a participant?'], 'P140': [1, 'Who or what entity is affiliated to the {} religion?'],
                  'P463': [2, 'Which {} is a member of {}?'], 'P364': [2, 'Which {} was originally in {}?'],
                  'P57': [2, 'Which {} was directed by {}?'], 'P410': [1, 'Who arrived to the rank {}?'],
                  'P1050': [1, 'Who suffered from {}?'],
                  'P101': [1, 'Who works in the {} industry?'], 'P1303': [1, 'Who played {}?'],
                  'P103': [1, 'Who has or had {} as its mother tongue?'], 'P162': [2, 'Which {} was produced by {}?'],
                  'P1923':[1, 'Which competitions had {} as participant?'],'P6193':[1, 'Which treaties were ratified by {}?'],
                  'P149': [1, 'Which buildings were built in {} style?'], 'P509': [1, 'Who died of {}?'],
                  'P1346': [2, 'Which {} were won by {}?'], 'P119': [1, 'Who is or was buried in {}?'],
                  'P86': [1, 'Which musics (including film musics) were composed by {}?'], 'P859': [2, 'Which {} is sponsored by{}?'],
                  'P452': [1, 'Which companies were in the {} industry?'], 'P61': [1, 'What entities were invented or discovered by {}?'],
                  'P1411': [1, 'Who was nominated for {}?'], 'P945': [1, 'Who serves or served {}?'],
                  'P97': [1, 'Who has or had the title {}?'], 'P144': [2, 'Which {} is based on {}?'],
                  'P467': [1, 'Which bill or laws were legislated by {}?'], 'P812': [1, 'Who majored in {}?'],
                  'P178': [2, 'Which {} was developed by {}?'],
                  'P306': [1, 'Which applications or hardwares ran on {}?'], 'P1049': [1, 'Which deities were worshipped by {}?'],
                  'P1080': [2, 'Which {} is from the {} universe?'], 'P189': [1, 'Which objects or species were discovered in {}?'],
                  'P1071': [2, 'Which {} was created in {}?'], 'P275': [2, 'Which {} had {} as a voice actor ?'],
                  'P527': [2, 'What {} are parts of {}?'], 'P641':[1, 'Who played the sport {}?'],
                  'P1344': [2, 'What {} participated in {}?'], 'P126': [1, "What entities were maintained by {}?"],
                  'P137': [1, 'What entities were operated by {}?'], 'P413': [1, "Who played the position {}?"],
                  'P2094': [2, 'What {} plays in the competition class {}?'], 'P123': [2, 'What {} was published by {}?'],
                  'P264': [2, 'Which {} is part of the record label {}?'], 'P937': [1, 'Who works or worked in {}?'],
                  'P184': [1, 'Who had {} as his/her doctoral advisor?'], 'P551': [1, 'Who resides or resided in {}?'],
                  'P291': [2, "What {} was published in {}?"], 'P7937': [1, 'What artworks were of the form {}?'],
                  'P607': [2, 'What {} took part in {}?'], 'P118': [2, 'What {} played in the league {}?'],
                  'P58': [2, 'Which {} had {} as screenwriter?'], 'P437': [2, 'Which {} was or is distributed via {}?'],
                  'P172': [1, 'Who was part of the ethnic group {}?'], 'P275': [2, 'What {} is under the copyright license {}?'],
                  'P750': [2, 'What {} is distributed by {}?'], 'P176': [1, 'What objects were manufactured by {}?'],
                  'P2079': [1, 'What objects were fabricated using the method {}?'], 'P1441': [2, 'Which {} is present in the work {}?'],
                  'P272': [2, 'What {} was produced by {}?'], 'P241': [2, 'What {} belongs to the military branch {}?'],
                  'P1196': [1, 'Who died in the following form {}?'], 'P344': [2, 'Which {} had {} as director of photography?'],
                  'P840': [2, 'What {} has its story located in {}?'], 'P449': [2, 'What {} was originally broadcasted by {}?'],
                  'P664': [2, 'What {} was organized by {}?'], 'P1066': [1, 'Who was a student of {}?'],
                  'P1071': [2, 'What {} was discovered or invented in {}?'], 'P206': [2, 'What {} is located next to {}?'],
                  'P485': [2, 'What {} has its archives stored in {}?'], 'P8047': [1, 'Which ships were registered in {}?'],
                  'P135': [1, 'Who was part of the movement {}?'], 'P725': [2, 'What {} had {} as its voice actor?'],
                  'P825': [1, 'What creations were dedicated to {}?'], 'P740': [1, 'Which groups were formed in {}?'],
                  'P767': [1, 'Which work or subject had {} as contributor?'], 'P676': [1, 'Which songs had its lyrics written by {}?'],
                  'P3018': [2, 'Which {} is located in the protected area {}?'], 'P658': [1, 'What song or album were part of the tracklist {}?'],
                  'P98': [2, 'What {} was edited by {}?'], 'P371': [1, 'What games were presented by {}?'],
                  'P611': [1, 'Who was part of the religious order {}?'], 'P8345': [2, 'What {} is part of the media franchise {}?'],
                  'P88': [2, 'What {} was commissioned by {}?'], 'P1142': [2, 'What {} adheres to the ideology {}?'],
                  'P547': [2, 'What {} commemorates {}?'], 'P532': [1, 'Which ships were registered in {}?'], 'P737': [1, 'Who was influenced by {}?'],
                  'P2341': [2, 'What {} is indigenous to {}?'], 'P2541': [2, 'What {} operates in {}?'],
                  'P655': [1, 'What texts were translated by {}?'], 'P1716': [2, 'What {} is from the brand {}?'],
                  'P2650': [1, 'Who or what organisations were interested in {}?'], 'P287': [1, 'Which objects were designed by {}?'],
                  'P110': [2, 'What {} was illustrated by {}'], 'P289': [1, 'What ships were of the vessel class {}?'],
                  'P2515': [2, 'What {} had {} as its costume designer?'], 'P647': [1, 'Who was drafted by {}?'],
                  'P6087': [1, 'Who coached the sports teams {}?'], 'P1399': [1, 'Who was convicted of {}?'],
                  'P4068': [2, 'What {} had {} as scenographer?'], 'P2596': [2, 'What {} is from the {} culture?'],
                  'P7153': [2, 'What {} is associated with {}?'], 'P1431': [2, 'What {} had {} as its executive producer?'],
                  'P1875': [1, 'Who was or is represented by {}?'], 'P3301': [2, 'What {} is broadcasted by {}?'],
                  'P1951': [1, 'Which companies had {} as investor?'], 'P736': [2, 'What {} has its covert art by {}?'],
                  'P504': [1, 'Which ships had {} as its home port?'], 'P6241': [1, 'What collections were created by {}?'],
                  'P520': [1, 'What military equipments had {} as one of its arms?'], 'P941': [2, 'What {} is inspired by {}?'],
                  'P4584': [2, 'What {} first appeared in {}?'], 'P1809': [1, 'Which dances were choreographed by {}?'],
                  'P6942': [1, 'What movie or clips were animated by {}?'], 'P618':[2, 'What {} uses {} as its source of energy?'],
                  'P3300': [1, 'Which musical groups (orchestra, chorus, etc..) were conducted by {}?'],
                  'P5202': [2, 'What {} was adapted by {}?'], 'P5028': [2, 'What {} had {} as its sound designer?'],
                  'P6872': [1, 'Who wrote for {}?'], 'P7936': [2, 'What {} runs with the business model {}?'],
                  'P2438': [1, 'Which stories were narrated by {}?'], 'P2652': [1, 'What organisations had a partnership with {}?'],
                  'P6338': [2, 'What {} has {} as its colorist?'], 'P3174': [2, 'What {} has {} as its art director?'],
                  'P6379': [1, 'Who has its works exposed in {}?']}


SUBJECT_MAPPING = defaultdict(lambda : 'human')
SUBJECT_MAPPING['P6193'] = 'treaties'
SUBJECT_MAPPING['P84'] = 'buildings'
SUBJECT_MAPPING['P149'] = 'buildings'
SUBJECT_MAPPING['P86'] = 'musics (including film musics)'
SUBJECT_MAPPING['P452'] = 'companies'
SUBJECT_MAPPING['P467'] = 'bill or laws'
SUBJECT_MAPPING['P189'] = 'objects or species'
SUBJECT_MAPPING['P1049'] = 'deities'
SUBJECT_MAPPING['P176'] = 'objects'
SUBJECT_MAPPING['P2079'] = 'objects'
SUBJECT_MAPPING['P8047'] = 'ships'
SUBJECT_MAPPING['P2652'] = 'organisations'
SUBJECT_MAPPING['P520'] = 'military equipments'
SUBJECT_MAPPING['P504'] = 'ships'
SUBJECT_MAPPING['P3300'] = 'musical groups (orchestra, chorus, etc..)'
SUBJECT_MAPPING['P371'] = 'games'
SUBJECT_MAPPING['P1951'] = 'companies'
SUBJECT_MAPPING['P289'] = 'ships'
SUBJECT_MAPPING['P287'] = 'objects'
SUBJECT_MAPPING['P655'] = 'texts'
SUBJECT_MAPPING['P532'] = 'ships'
SUBJECT_MAPPING['P658'] = 'songs or albums'
SUBJECT_MAPPING['P676'] = 'songs'

COMP_PROPERTIES = {'P577': 'publication dates', 'P1433': 'publication years',
                   'P569': 'dates of birth', 'P570': 'dates of death', 'P571': 'inception years',
                   'P1082': 'populations', 'P195': 'collections', 'P40': 'children of',
                   'P1001': 'jurisdictions applying', 'P22': 'fathers', 'P2048': 'heights', 'P26': 'spouses',
                   'P2046': 'aresa', 'P25': 'mothers', 'P1463': 'collection or exhibition sizes', 'P1132': 'number of participants',
                   'P3373': 'siblings', 'P7763': 'copyright status', 'P138': 'named after', 'P2067': 'masses',
                   'P185': 'doctoral students', 'P1540': 'male populations', 'P1539':'female populations',
                   'P576': 'dissolution, abolition or demolition years', 'P1538': 'numbers of households', 'P2348': 'time periods',
                   'P2561': 'names', 'P3602': 'candidacies in election', 'P2047': 'durations', 'P3872': 'patronages',
                   'P4080': 'numbers of houses', 'P36': 'capitals', 'P241': 'military branches', 'P6499': 'literate populations',
                   'P6498': 'illiterate populations', 'P800': 'notable works', 'P355': 'subsidiaries', 'P674': 'characters',
                   'P1128': 'numbers of employees', 'P1120': 'numbers of death', 'P575': 'years of discovery or invention', 'P729': 'service entry years',
                   'P112': 'years of foundation', 'P2196': 'students counts', 'P5630': 'prisoners counts', 'P802': 'students',
                   'P2754': 'production year', 'P1113': 'number of episodes', 'P1191': 'year of first performance',
                   'P2124': 'member counts', 'P1174': 'numbers of visitors per year', 'P511': 'honorific prefixes', 'P457': 'foundational texts',
                   'P1350': 'numbers of matches played/races starts', 'P2936': 'languages used', 'P1971': 'numbers of children',
                   'P2437': 'numbers of seasons', 'P115': 'home venues', 'P5816': 'states of conservation', 'P915': 'filming locations',
                   'P2962': 'chess titles', 'P5817': 'states of use', 'P3157': 'distances parcoured during', 'P1618': 'jersey numbers',
                   'P1110': 'attendance', 'P1083': 'maximum capacities', 'P177': 'crossed', 'P417': 'patron saints',
                   'P4519': 'payload masses', 'P6343': 'urban populations', 'P4969': 'derivative works', 'P2522': 'events won by',
                   'P1536': 'immediate causes of', 'P912': 'facilities', 'P6344': 'rural populations',
                   'P6885': 'historical regions', 'P1027': 'conferred by', 'P1092': 'total amounts produced', 'P1101': 'numbers of floors above ground',
                   'P414': ' market places where the stock is exchanged', 'P1867': 'numbers of eligible voters', 'P121':'items operated', 'P931': 'places served ',
                   'P1877': 'artist of creations that inspired', 'P277': 'base codes programming language', 'P2505': 'items carried', 'P6509': 'numbers of total goals',
                   'P803': 'professor positions', 'P516': 'power sources', 'P2109': 'installed capacities', 'P1299': 'creations that depicts',
                   'P1434':'fictional universes', 'P1028': 'donors', 'P730': 'years of service retirement',
                   'P1451':'motto texts', 'P2130':'costs', 'P1026': 'thesis', 'P1990': 'species kept', 'P530': 'diplomatic relations',
                   'P2130': 'movie budgets', 'P2403': 'total values of assets', 'P741':'playing hands', 'P610': 'highest points',
                   'P2121': 'prize money', 'P1268': 'entities represented by', 'P2295': 'net profits', 'P1373': 'daily patronages',
                   'P5800': 'narrative roles', 'P3320': 'board members', 'P765': 'surfaces played on', 'P2402': 'total expenditures',
                   'P157': 'killers', 'P2284': 'prize', 'P1029': 'crew members', 'P2142': 'box offices', 'P872': 'printers',
                   'P2138': 'total values of liabilities', 'P1098': 'numbers of speakers', 'P5769': 'editors in chief',
                   'P942': 'theme musics', 'P798': 'military designations', 'P7779': 'military units',
                   'P2218': 'net worth', 'P50': 'authors', 'P131': 'locations', 'P407': 'original languages', 'P106': 'occupations',
                   'P21': 'sexes or genders', 'P27': 'citizenships', 'P19': 'places of birth', 'P276': 'locations',
                   'P69': 'education places', 'P1412': 'languages spoken, written or signed', 'P527': 'parts', 'P641':'sports played',
                   'P108': 'employers', 'P136': 'genres', 'P39': 'positions held', 'P161': 'cast members',
                   'P495': 'countries of origin', 'P166': 'awards received', 'P20': 'places of death', 'P186': 'base materials',
                   'P170': 'creators', 'P180': 'depicted entities', 'P126': 'maintainers', 'P137': 'operators', 'P175': 'performers',
                   'P102': 'political parties', 'P127': 'owners', 'P140': 'religions', 'P159': 'headquarter locations',
                   'P710': 'participants', 'P463': 'main group', 'P413': 'positions played', 'P364': 'original languages',
                   'P2094': 'competition classes', 'P123': 'publishers', 'P2868': 'roles', 'P264':'record labels',
                   'P937': 'work locations', 'P57': 'directors', 'P184': 'doctoral advisors', 'P551': 'residence locations',
                   'P103': 'native languages', 'P291': 'places of publication', 'P1050': 'medical conditions', 'P1346': 'winners',
                   'P101': 'fields of work', 'P7937': 'forms of work', 'P607': 'conflicts fought', 'P119': 'places of burial',
                   'P1303': 'instruments played', 'P86': 'composers', 'P118': 'leagues', 'P58': 'screenwriters', 'P437': 'distribution formats',
                   'P162': 'producers', 'P859': 'sponsors', 'P172': 'ethnicities', 'P275': 'copyright licenses', 'P750': 'distributors',
                   'P1923': 'participating team', 'P512': 'academic degrees', 'P176': 'manufacturers',
                   'P149': 'architectural styles', 'P2079': 'fabrication methods', 'P1441': 'creative works',
                   'P272': 'production companies', 'P509': 'causes of death', 'P241': 'military branches',
                   'P1196': 'manners of death', 'P452': 'industries', 'P344': 'directors of photography',
                   'P840': 'narrative locations', 'P449': 'original broadcasters', 'P664': 'organizers',
                   'P1066': 'teachers', 'P1071': 'locations of creation', 'P206': 'close body water',
                   'P84': 'architects', 'P485': 'archives location', 'P1411': 'nominations', 'P8047': 'countries of registry',
                   'P945': 'allegiances', 'P135': 'movements', 'P725': 'voice actors', 'P97': 'noble titles',
                   'P144': 'bases', 'P825': 'dedications', 'P467': 'legislators', 'P740': 'locations of formation',
                   'P178': 'developers', 'P767': 'contributors', 'P676': 'lyrics writer',
                   'P658': 'tracklists', 'P98': 'editors', 'P371': 'presenters',
                   'P611': 'religious orders', 'P1080': 'original narrative universe', 'P189': 'locations of discovery',
                   'P8345': 'media franchises', 'P88': 'commissioners', 'P1142': 'political ideologies',
                   'P547': 'commemorated events', 'P532': 'ports of registry', 'P737': 'influences',
                   'P2341': 'indigenous locations', 'P2541': 'operating areas', 'P655': 'translators', 'P1716': 'brands',
                   'P2650': 'interesting entities', 'P287': 'designers', 'P110': 'illustrators', 'P289': 'vessel classes',
                   'P2515': 'costume designers', 'P647': 'drafting teams', 'P6087': 'coaches',
                   'P1399': 'convictions', 'P4068': 'scenographer', 'P2596': 'original culture',
                   'P7153': 'significant places', 'P1431': 'executive producers', 'P1875':'representatives',
                   'P3301': 'broadcasters', 'P1951': 'investors', 'P736': 'cover artist', 'P504': 'home ports',
                   'P6241':'collection creators', 'P520': 'armaments', 'P941': 'inspirations', 'P4584': 'first appearances',
                   'P1809': 'choreographers', 'P6942': 'animators', 'P618': 'sources of energy', 'P3300': 'musical conductors',
                   'P5202': 'adapters', 'P5028': 'sound designers', 'P6872': 'writing clients', 'P812': 'academic majors',
                   'P6193': 'ratifiers', 'P7936': 'business models', 'P1049': 'worshippers', 'P2438':'narrators',
                   'P2652': 'partners', 'P6338': 'colorists', 'P3174': 'art directors', 'P6379': 'collection exposed to',
                   'P410': 'military ranks', 'P54': 'teams', 'P61': 'discoverers or inventors', 'P306': 'Operating systems'}

# 1 ans, ori, prop
# 2 ans, prop, ori
# 3

MNLI_COMP_SENT = {'P800##P802##P915##P4969##P1028##P3320##P1029': [1, "{} is one of {}'s {}."],
             'P195##P1434##P530': [1, "{} is a part of {}'s {}."],
             'P1001##P1536##P121##P1877': [2, "{} is the {} {}."],
             'P138##P1027##P1092##P121##P931##P2505##P2522##P177##P2936##P1299##P1268': [2, "{} is {} {}."],
             'P674': [2, "{} is a {} from {}."],
             'P3602': [2, "{} was a {} in {}."],
             'P2936##P177##P2522##P2505': [2, "{} is {} by {}."],
             'P3157': [2, "{} is the {} {}."]}

MNLI_COMP = {'P577': 'publication date', 'P1433': 'publication year',
             'P569': 'date of birth', 'P570': 'date of death', 'P571': 'inception year',
             'P1082': 'population', 'P195': 'collection', 'P40': 'child',
             'P1001': 'jurisdictions applying to', 'P22': 'father', 'P2048': 'height', 'P26': 'spouse',
             'P2046': 'area', 'P25': 'mother', 'P1463': 'collection or exhibition size', 'P1132': 'number of participants',
             'P3373': 'sibling', 'P7763': 'copyright status', 'P138': 'named after', 'P2067': 'mass',
             'P185': 'doctoral student', 'P1540': 'male population', 'P1539':'female population',
             'P576': 'dissolution, abolition or demolition year', 'P1538': 'number of households', 'P2348': 'time period',
             'P2561': 'name', 'P3602': 'candidate', 'P2047': 'duration', 'P3872': 'patronage',
             'P4080': 'number of houses', 'P36': 'capital', 'P241': 'military branch', 'P6499': 'literate population',
             'P6498': 'illiterate population', 'P800': 'notable work', 'P355': 'subsidiary', 'P674': 'character',
             'P1128': 'number of employees', 'P1120': 'number of death', 'P575': 'year of discovery or invention', 'P729': 'service entry years',
             'P112': 'year of foundation', 'P2196': 'students count', 'P5630': 'prisoners count', 'P802': 'student',
             'P2754': 'production year', 'P1113': 'number of episodes', 'P1191': 'year of first performance',
             'P2124': 'member count', 'P1174': 'number of visitors per year', 'P511': 'honorific prefix', 'P457': 'foundational text',
             'P1350': 'number of matches played/races starts', 'P2936': 'the language used by', 'P1971': 'number of children',
             'P2437': 'number of seasons', 'P115': 'home venue', 'P5816': 'state of conservation', 'P915': 'filming location',
             'P2962': 'chess title', 'P5817': 'state of use', 'P3157': 'distance traveled during', 'P1618': 'jersey number',
             'P1110': 'attendance', 'P1083': 'maximum capacity', 'P177': 'crossed by', 'P417': 'patron saint',
             'P4519': 'payload mass', 'P6343': 'urban population', 'P4969': 'derivative work', 'P2522': 'an event won by',
             'P1536': 'immediate cause of', 'P912': 'facility', 'P6344': 'rural population',
             'P6885': 'historical region', 'P1027': 'conferred by', 'P1092': 'the total amount produced of', 'P1101': 'number of floors above ground',
             'P414': 'stock exchange market place', 'P1867': 'number of eligible voters', 'P121': 'an item operated by', 'P931': 'a place served by',
             'P1877': 'artist of creations that inspired', 'P277': 'base code programming language', 'P2505': 'an item carried by', 'P6509': 'number of total goals',
             'P803': 'professor position', 'P516': 'power source', 'P2109': 'installed capacity', 'P1299': 'a creation that depicts',
             'P1434':'fictional universe', 'P1028': 'donor', 'P730': 'year of service retirement',
             'P1451':'motto text', 'P2130':'cost', 'P1026': 'thesis', 'P1990': 'the species kept by', 'P530': 'diplomatic relation',
             'P2130': 'budget', 'P2403': 'assets value', 'P741':'playing hand', 'P610': 'highest point',
             'P2121': 'prize money', 'P1268': 'represented by', 'P2295': 'net profit', 'P1373': 'daily patronage',
             'P5800': 'narrative role', 'P3320': 'board member', 'P765': 'the surface played on in the sport', 'P2402': 'total expenditure',
             'P157': 'killer', 'P2284': 'prize', 'P1029': 'crew members', 'P2142': 'box office', 'P872': 'printer',
             'P2138': 'value of liabilities', 'P1098': 'number of speakers', 'P5769': 'editor in chief',
             'P942': 'theme music', 'P798': 'military designation', 'P7779': 'military unit',
             'P2218': 'net worth'}


COMP_SENTENCES = {0: [['P1476', 'P577', 'P1433', 'P17', 'P569', 'P734', 'P570', 'P571', 'P1082', 'P195', 'P281', 'P2048',
                       'P2046', 'P1463', 'P1132', 'P7763', 'P138', 'P2067', 'P1540', 'P1539', 'P576', 'P1538', 'P2348',
                       'P2561', 'P3602', 'P2047', 'P3872', 'P4080', 'P36', 'P241', 'P6499', 'P6498', 'P800', 'P355',
                       'P1128', 'P1120', 'P575', 'P729', 'P112', 'P2196', 'P5630', 'P2754', 'P1113', 'P1191', 'P2124',
                       'P1174', 'P511', 'P457', 'P1350', 'P2936', 'P1971', 'P2437', 'P115', 'P5816', 'P915', 'P2962',
                       'P5817', 'P3157', 'P1618', 'P1110', 'P1083', 'P417', 'P4519', 'P6343', 'P4969', 'P1536', 'P6344',
                       'P6885', 'P1092', 'P1101', 'P414', 'P1867', 'P277', 'P6509', 'P803', 'P516', 'P2109', 'P730', 'P1451',
                       'P2130', 'P530', 'P2130', 'P2403', 'P741', 'P610', 'P2121', 'P2295', 'P1373', 'P5800', 'P2402', 'P2284',
                       'P2142', 'P2138', 'P1098', 'P942', 'P798', 'P7779', 'P2218', 'P50', 'P131', 'P407', 'P106', 'P21',
                       'P27', 'P19', 'P276', 'P69', 'P527', 'P108', 'P136', 'P39', 'P495', 'P20', 'P186', 'P1344', 'P126',
                       'P137', 'P175', 'P102', 'P140', 'P159', 'P463', 'P364', 'P2094', 'P2868', 'P264', 'P937', 'P551',
                       'P103', 'P291', 'P1050', 'P101', 'P7939', 'P119', 'P118', 'P437', 'P172', 'P275', 'P750', 'P512',
                       'P149', 'P2079', 'P272', 'P509', 'P241', 'P1196', 'P452', 'P840', 'P1071', 'P485', 'P1411', 'P8047',
                       'P945', 'P135', 'P97', 'P144', 'P825', 'P467', 'P740', 'P658', 'P611', 'P1080', 'P189', 'P8345',
                       'P532', 'P737', 'P2341', 'P2541', 'P1716', 'P289', 'P647', 'P1399', 'P2596', 'P504', 'P520', 'P941',
                       'P4584', 'P618', 'P6872', 'P812', 'P6193', 'P7936', 'P410', 'P54', 'P306'],['What', 'of']],
                  1: [['P1433', 'P1001', 'P206'], ['What', 'to']],
                  2: [['P22', 'P40', 'P26', 'P25', 'P3373', 'P185', 'P674', 'P802', 'P1028', 'P3320', 'P157', 'P1029', 'P872',
                       'P5769', 'P161', 'P166', 'P170', 'P127', 'P123', 'P57', 'P184', 'P1346', 'P86', 'P58', 'P162',
                       'P859', 'P176', 'P344', 'P449', 'P664', 'P1066', 'P84', 'P275', 'P178', 'P767', 'P676', 'P98',
                       'P371', 'P88', 'P1142', 'P655', 'P287', 'P110', 'P2515', 'P6087', 'P4086', 'P1431', 'P1875', 'P3301',
                       'P1951', 'P736', 'P6241', 'P1809', 'P6942', 'P3300', 'P5202', 'P5028', 'P1049', 'P2438', 'P2652',
                       'P6338', 'P3174', 'P61'], ['Who', 'of']],
                  3: [['P800', 'P177', 'P2522', 'P121', 'P931', 'P2505', 'P1026', 'P1990', 'P765', 'P1412', 'P641', 'P180',
                       'P413', 'P607', 'P1303', 'P1441', 'P547', 'P6379'], ['What', 'by']],
                  4: [['P912', 'P710', 'P1923',], ['What', 'in']], 5:[['P1877'], ['Who', 'the']],
                  6: [['P2650', 'P7153'], ['What', 'for']],
                  6: [['P1299', 'P1268'], ['What', 'the']], 7: [['P1434'], ['What', 'where are']]}

FOR_SIMPLE = list(SELECTED_PRORPERTIES.keys())

FOR_COMPOSITION = list(COMP_PROPERTIES.keys())

ALL_PROPERTIES = FOR_SIMPLE + FOR_COMPOSITION

SUBCLASSES = {
    'P131': ['human settlement', 'building', 'infrastructure', 'economy', 'social system', 'territorial entity',
             'spatial entity'],
    'P361': ['nonprofit organization', 'building', 'infrastructure', 'human settlement', 'person', 'creative work',
             'competition', 'business', 'company', 'educational organization'],
    'P276': ['work of art', 'nonprofit organization', 'business', 'company', 'competition', 'building',
             'infrastructure', 'natural geographical entity', 'cultural heritage', 'person', 'social phenomenon',
             'educational organization'],
    'P136': ['person', 'film', 'play', 'painting', 'game', 'song', 'musical work', 'visual artwork', 'artwork',
             'building'], 'P162': ['film', 'song', 'television series', 'album', 'creative work'],
    'P859': ['award', 'person', 'nonprofit organization', 'business', 'company', 'competition', 'equipment',
             'educational organization'],
    'P144': ['software', 'visual artwork', 'creative work'],
    'P31': ['nonprofit organization', 'competition', 'building', 'infrastructure', 'award', 'person',
            'human settlement',
            'territorial entity', 'creative work', 'business', 'company', 'educational organization'],
    'P180': ['painting', 'symbol', 'building', 'cultural heritage', 'collectible', 'visual artwork'],
    'P2868': ['person', 'building', 'infrastructure', 'chemical substance', 'business', 'nonprofit organization',
              'company', 'educational organization'],
    'P5028': [],
    'P6338': ['creative work'],
    'P175': ['song', 'album', 'film', 'musical group', 'creative work'],
    'P5202': [],
    'P127': ['facility', 'building', 'infrastructure', 'vehicle', 'business', 'nonprofit organization', 'company',
             'intellectual work', 'educational organization'],
    'P159': ['competition', 'company', 'institute', 'business', 'nonprofit organization', 'company', 'technology'],
    'P710': ['election', 'competition', 'conflict', 'agreement', 'historical event', 'era'],
    'P1346': ['election', 'competition', 'conflict', 'historical event'],
    'P463': ['sport organization', 'company', 'business', 'company', 'nonprofit organization', 'person',
             'educational organization'],
    'P364': ['film', 'television series', 'literary work', 'creative work', 'language', 'idiom'],
    'P407': ['film', 'television series', 'literary work', 'creative work', 'language', 'idiom'],
    'P437': ['film', 'television series', 'song', 'album', 'creative work'],
    'P57': ['film', 'television series', 'song', 'album', 'creative work'],
    'P344': ['film', 'television program', 'audiovisual work'],
    'P3018': ['landform', 'human settlement', 'building', 'work of art'],
    'P547': ['monument', 'museum', 'achitectural structure'],
    'P750': ['film', 'television program', 'audiovisual work', 'application'],
    'P3174': ['event'],
    'P272': ['film', 'animated series','series','television program'],
    'P1441': ['fictional character'],
    'P98': ['written work'],
    'P607': ['human', 'military operation'],
    'P1431': ['television program', 'film', 'audiovisual work'],
    'P2341': ['language', 'ethnic group', 'clothing', 'art'],
    'P2596': ['language', 'ethnic group', 'clothing', 'art'],
    'P527': ['food', 'musical group', 'geographic region', 'chemical substance'],
    'P618': ['building'],
    'P3301': ['event', 'television program', 'award', 'audiovisual work'],
    'P241': ['person', 'military base', 'military unit'],
    'P2515': ['film', 'television program', 'audiovisual work', 'dance'],
    'P88': ['work of art', 'building', 'military base', 'architectural structure'],
    'P2094': ['competition'],
    'P264': ['album', 'musical ensemble', 'person', 'song'],
    'P7936': ['organization'],
    'P1716': ['automobile model', 'physical good'],
    'P941': ['video game', 'video game character'],
    'P4584': ['fictional character', 'fictional entity'],
    'P110': ['comics', 'written work'],
    'P840': ['film', 'written work', 'television program', 'creative work'],
    'P1142': ['political movement', 'armed organization', 'organization'],
    'P206': ['landform', 'country', 'geographic entity', 'human settlement', 'island', 'park', 'building'],
    'P58': ['television program', 'film'],
    'P8345': ['video game', 'film', 'television program', 'fictional character'],
    'P485': ['creator'],
    'P1344': ['person', 'entity in event'],
    'P725': ['voice actor'],
    'P449': ['television program'],
    'P7153': ['heritage site', 'natural park', 'geographic feature', 'geographic entity'],
    'P123': ['written work', 'literary work', 'video game'],
    'P291': ['newspaper', 'news media', 'written work'],
    'P2541': ['business', 'organization', 'political party', 'competition', 'television station'],
    'P736': ['literary work', 'musical work', 'album'],
    'P664': ['sports organization', 'convention', 'event', 'award'],
    'P161': ['film', 'television series', 'play'], 'P275': ['film', 'television series', 'play', 'fictional character'],
    'P186': ['food', 'visual artwork', 'building', 'infrastructure', 'natural geographic object', 'creative work'],
    'P495': ['food', 'film', 'visual artwork', 'music', 'infrastructure', 'technology', 'creative work'],
    'P170': ['fictional character', 'musical work', 'visual artwork', 'literary work', 'audiovisual work',
             'performance work', 'nonprofit organization', 'company', 'business', 'educational organization'],
    'P178': ['application', 'software', 'software company', 'nonprofit organization', 'company', 'business',
             'creative work', 'educational organization'],
    'P1080': ['fictional character', 'fictional vehicle', 'fictional object'],
    "P1071": ['painting', 'vehicle', 'creative work', 'intellectual work'],
    'P118': ['sports club', 'sports organization', 'sports team'],
    }

DESIRED_SUBCLASSES = {'architectural structure', 'agreement', 'album', 'animated series', 'application',
                      'architectural structure', 'armed organization', 'art', 'artwork', 'audiovisual work',
                      'automobile model', 'award', 'building', 'business', 'chemical substance', 'clothing', 'collectible',
                      'comics', 'company', 'competition', 'conflict', 'convention', 'country', 'creative work', 'creator',
                      'cultural heritage', 'dance', 'economy', 'educational organization', 'election', 'entity in event',
                      'equipment', 'era', 'ethnic group', 'event', 'facility', 'fictional character', 'fictional entity',
                      'fictional object', 'fictional vehicle', 'film', 'food', 'game', 'geographic entity', 'geographic feature',
                      'geographic region', 'heritage site', 'historical event', 'human', 'human settlement', 'idiom',
                      'infrastructure', 'institute', 'intellectual work', 'island', 'landform', 'language', 'literary work',
                      'military base', 'military operation', 'military unit', 'monument', 'museum', 'music', 'musical ensemble',
                      'musical group', 'musical work', 'natural geographic object', 'natural geographical entity', 'natural park',
                      'news media', 'newspaper', 'nonprofit organization', 'organization', 'painting', 'park','performance work',
                      'person', 'physical good', 'play', 'political movement', 'political party', 'series', 'social phenomenon',
                      'social system', 'software', 'software company', 'song', 'spatial entity', 'sport organization',
                      'sports club', 'sports organization', 'sports team', 'symbol', 'technology', 'television program',
                      'television series', 'television station', 'territorial entity', 'vehicle','video game',
                      'video game character', 'visual artwork', 'voice actor', 'work of art', 'written work'}

REPHRASING = {"creative work": "software, art, etc.",
              "territorial entity": "natural area, domicile or venue",
              "visual artwork": "paintings, sculptures, monuments etc.",
              "social phenomenon": "conflict, revolt, attack etc.",
              "social system": "market,economy etc.", "audiovisual work": "movie, clip, TV show etc.",
              "intellectual work": "creative work including creative organizations such as newspapers, radio stations, etc",
              "economy": "economic entity", "cultural heritage": "cultural heritage entity"}

POSSIBLE_TYPES = {'agreement', 'album', 'application', 'artwork', 'movie, clip, TV show etc.', 'award',
                  'building', 'chemical substance', 'collectible', 'company', 'competition', 'conflict',
                  'creative work (software, art, etc.)',
                  'cultural heritage entity', 'economic entity', 'election', 'equipment', 'era', 'facility',
                  'fictional character',
                  'musical work', 'fictional object', 'fictional vehicle', 'film', 'food', 'game', 'historical event',
                  'human settlement', 'idiom', 'infrastructure', 'institute',
                  'creative work including creative organizations such as newspapers, radio stations, etc',
                  'language', 'literary work', 'musical group', 'natural geographic object',
                  'natural geographical entity',
                  'nonprofit organization', 'painting', 'performance work', 'person', 'play',
                  'conflict, revolt, attack etc.',
                  'market,economy etc.', 'software', 'software company', 'song', 'spatial entity', 'sport organization',
                  'symbol', 'technology', 'television series', 'natural area, domicile or venue', 'vehicle',
                  'paintings, sculptures, monuments etc.', 'work of art', 'business', 'company',
                  'educational organization'}

INVERSE_PROPERTY_ENUM = {v: k for k, v in SELECTED_PRORPERTIES.items()}
